### ISSUE TITLE
An error occurred while reading .nurpdb

### ISSUE THREAD

**Issue by kjjkjjzyayufqza** [ultimate-research/ssbh_lib#154]
Thank you for writing such a powerful tool. Recently, when I tried to run the following command 
`ssbh_lib_json.exe ferenderer_rt.nurpdb`
an error occurred: 
BinRead(bad magic at 0x0: [12, 0, 0, 0])
![image](https://github.com/user-attachments/assets/783d4b73-3b26-415b-908e-099ccd903300)

Attached is this file. If you have time to look at it, it would be greatly appreciated!
[ferenderer_rt.zip](https://github.com/user-attachments/files/18091773/ferenderer_rt.zip)

**Comment by ScanMountGoat** [comment]
What game is this from? The binary format appears to be totally different than the modern namco formats that start with an HBSS magic. The pointer and array count fields are 32 instead of 64 bits, the magic is NRPD instead of DPRN, etc. The data should be similar to the existing structs in nrpd.rs if you want to create your own parser.

**Comment by kjjkjjzyayufqza** [comment]
> What game is this from? The binary format appears to be totally different than the modern namco formats that start with an HBSS magic. The pointer and array count fields are 32 instead of 64 bits, the magic is NRPD instead of DPRN, etc. The data should be similar to the existing structs in nrpd.rs if you want to create your own parser.

Thank you very much for your time,
This file is what I extracted from Mobile Suit Gundam Extreme Vs. 2, `.nufxlb` and `.nushdb` are working fine, but only `.nurpdb` is weird.
